### PR TITLE
Add Daily Log app

### PR DESCRIPTION
**Pull request by joemasilotti**

### CODE REVIEW

**Review by williamkennedy — APPROVED** [review]
Looks good Joe

**Comment by joemasilotti** [comment]
Thanks for the merge, @williamkennedy! What do we need to do to get this deployed?

**Comment by robzolkos** [comment]
Im on it shortly.  Its manual at the moment. Gotta figure out how to do the kamal deploy step in CI 😆

**Comment by robzolkos** [comment]
@joemasilotti deployed. sorry for the delay.

**Comment by joemasilotti** [comment]
Awesome! Thanks Rob.

**Pull request merged**
